import type { Metadata } from 'next'
import { Josefin_Sans, Poppins } from 'next/font/google'
import './globals.css'
import { Providers } from './Provider'
import { ThemeProvider } from './utils/theme-provider'

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${josefinSans.className} ${poppins.className}`}>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  )
}